name: Tests

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --ignore-platform-reqs"
  PHPUNIT_EXCLUDE_GROUP: mssql,oci,wincache,xcache,zenddata,cubrid
  CC_TEST_REPORTER_ID: 106fb842ef18f24de395ad9b8469c4eeac8f7a18026c7e8c59f969ec6885a83c
jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['7.3', '7.4', '8.0']

    steps:
      ## checkout the repoistory 
      - name: Checkout Repo
        uses: actions/checkout@v2

      ## Install(?) php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apc, curl, dom, intl, mbstring, mcrypt
          ini-values: date.timezone='UTC'

      ## install composer
      - name: Install dependencies
        run: composer install $DEFAULT_COMPOSER_FLAGS

      ## run unit tests
      - name: PHP Unit tests for PHP 
        run: vendor/bin/phpunit --verbose --configuration actions.phpunit.xml
        if: matrix.php == '7.4' || matrix.php == '7.3' || matrix.php == '7.2' || matrix.php == '7.0'

      ## unit test with coverage
      - name: PHP Unit tests for PHP 7.3
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --verbose --coverage-clover=clover.xml --configuration actions.phpunit.xml
        if: matrix.php == '7.3'

      ## coverage
      - name: Code coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build -t clover
        if: matrix.php == '7.3'
        continue-on-error: true # if is fork